### ISSUE TITLE
No such file or directory './templates'

### ISSUE THREAD

**Issue by jqtrde** [dshaw/blogit#1]
Started off with:

```
git clone https://github.com/dshaw/blogit.git
cd blogit
npm install
node blog.js
```

Returns the following:

```
fs.js:400
  return binding.readdir(pathModule._makeLong(path));
                 ^
Error: ENOENT, no such file or directory './templates'
    at Object.readdirSync (fs.js:400:18)
    at loadFolder_ (/home/jacques/blogit/node_modules/templar/templar.js:154:6)
    at Function.loadFolder (/home/jacques/blogit/node_modules/templar/templar.js:144:3)
    at blog (/home/jacques/blogit/blog.js:28:13)
    at Object.<anonymous> (/home/jacques/blogit/blog.js:18:5)
    at Module._compile (module.js:446:26)
    at Object..js (module.js:464:10)
    at Module.load (module.js:353:31)
    at Function._load (module.js:311:12)
    at Array.0 (module.js:484:10)
```

Noob here, so not really sure what to make of this...

**Comment by DTrejo** [comment]
+1
:smiley:

**Comment by dshaw** [comment]
@jacquestardie Thanks. Still finishing the module. We're doing a hands-on session with @substack for Voxer's [Summer of Node.js](https://twitter.com/summerofnodejs/) about Publishing Modules to NPM, so I rushed the publish before the module was fully baked.

I'll get the final code up later today. :)

**Comment by dshaw** [comment]
Fixed. It's still early days with this project, but it is now fully functional. Check out [summerofnodejs-blog](https://github.com/voxer/summerofnodejs-blog) for an example of how we are using this at @Voxer.

http://summerofnodejs.com/

**Comment by jqtrde** [comment]
Pulled the latest version, still getting the following

```
fs.js:400
  return binding.readdir(pathModule._makeLong(path));
             ^
Error: ENOENT, no such file or directory './templates'
    at Object.readdirSync (fs.js:400:18)
    at loadFolder_ (/home/jacques/blogit/node_modules/templar/templar.js:154:6)
    at Function.loadFolder (/home/jacques/blogit/node_modules/templar/templar.js:144:3)
    at blog (/home/jacques/blogit/blog.js:54:11)
    at Object.<anonymous> (/home/jacques/blogit/blog.js:37:3)
    at Module._compile (module.js:446:26)
    at Object..js (module.js:464:10)
    at Module.load (module.js:353:31)
    at Function._load (module.js:311:12)
    at Array.0 (module.js:484:10)
```

Cloned https://github.com/voxer/summerofnodejs-blog, which does work. Is it just that the templates folder is missing still?

**Comment by jqtrde** [comment]
Yea, that's all it is. Copied over the templates dir from https://github.com/voxer/summerofnodejs-blog to blogit, which works aside from some template errors.
